### ISSUE TITLE
msys2 compilation error

### ISSUE THREAD

**Issue by checo06** [brummer10/guitarix#159]
Before posting the issue i want to thank @brummer10 for this software.. this pieces of artwork makes me be very thankful and respectful about open source

I have been using guitarix on ubuntu studio with great joy. I started to use more Carla with the guitarix LV2 plugins and works great there also.

The issue is that i also use windows and wanted to compile the LV2 of guitarix with the msys2. I followed the /README.mswin with MinGW64 and had an error:

```
19:41:46 runner 'git submodule update --init --recursive'
Traceback (most recent call last):
  File "<string>", line 55, in <module>
  File "<string>", line 20, in run
OSError: [Errno 22] Invalid argument
Checking for git submodule               : up to date
Checking for 'g++' (C++ compiler)        : 19:41:47 runner ['C:\\msys64\\mingw64\\bin/g++.exe', '-dM', '-E', '-']
not found
```

The g++ is there, so i dont know why is not recognizing it.

This is the output of a ```g++ -v```

```
$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-14.1.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=nocona --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,rust,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-lto --enable-libgomp --disable-libssp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-libstdcxx-debug --enable-plugin --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstdc++
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 14.1.0 (Rev3, Built by MSYS2 project)
```

**Comment by brummer10** [comment]
This work is done by @torte71 
maybe he could give some hints.
But as you get a Traceback already before the g++ check, it may be related to some changes I've introduced after @torte71 work.

**Comment by checo06** [comment]
ok ok, in the meanwhile i got them from here:

https://www.reddit.com/r/Guitarix/comments/zqjfma/compiling_guitarixgxplugins_lv2_plugins_for/
